# Generated by Django 6.0.3 on 2026-07-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_restaurant_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='platform_fee_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
    ]
