# Generated by Django 6.0.3 on 2026-07-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_delivery_location_order_delivery_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='platform_fee_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
